### ISSUE TITLE
Issue with saveOptions and margins

### ISSUE THREAD

**Issue by azerios** [aspose-pdf/Aspose.PDF-for-.NET#31]
Dear,

By exporting a document created by Aspose.Cells, I want to share an issue.

If you setup pageOptions margin with right and left borders at 0.1 the export is more at the left with a right border like 0.5 margin and a real 0.1 margin at the left.

As a workaround I setup both margin at 0.5 but this default behavior is weird.

Is it possible to review my issue ?

Regards

**Comment by asadalikhan90** [comment]
@azerios 

Sorry for the delayed response. Would you please create a topic in our [official support forum](https://forum.aspose.com/c/pdf) which is the right place to discuss such matters? Please create a post there with your sample document and the code snippet so that we can address it accordingly.

**Comment by ilyazhuykov** [comment]
Since there have been no updates or additional questions for more than half a year, the issue is considered resolved.
